# Generated by Django 3.1.13 on 2021-08-26 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GravityTable',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nama_proyek', models.CharField(max_length=100, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('x', models.TextField(null=True)),
                ('y', models.TextField(null=True)),
                ('z', models.TextField(null=True)),
                ('freeair', models.TextField(null=True)),
                ('density', models.TextField(null=True)),
                ('sba', models.TextField(null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
