# Generated by Django 3.1.13 on 2021-08-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('data', models.FileField(default='DEFAULT', upload_to='upload/')),
            ],
        ),
        migrations.CreateModel(
            name='RowData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=100)),
                ('y', models.CharField(max_length=100)),
                ('z', models.CharField(max_length=100)),
                ('FA', models.CharField(max_length=100)),
            ],
        ),
    ]
