# Generated by Django 3.1.13 on 2021-08-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gravitytable',
            name='url_name',
            field=models.TextField(null=True),
        ),
    ]
