# Generated by Django 3.1.13 on 2021-08-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowdata',
            name='FA',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='rowdata',
            name='x',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='rowdata',
            name='y',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='rowdata',
            name='z',
            field=models.TextField(null=True),
        ),
    ]
