# Generated by Django 3.1.13 on 2021-08-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0002_auto_20210810_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengirim', models.CharField(max_length=100)),
                ('data_input', models.FileField(default='DEFAULT', upload_to='upload/')),
                ('delimiter', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='RowData',
            new_name='GravityTable',
        ),
        migrations.DeleteModel(
            name='Grav',
        ),
    ]
