# Generated by Django 3.1.13 on 2021-08-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0002_gravitytable_url_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gravitytable',
            old_name='sba',
            new_name='sba1',
        ),
        migrations.AddField(
            model_name='gravitytable',
            name='sba2',
            field=models.TextField(null=True),
        ),
    ]
