# Generated by Django 3.1.13 on 2021-09-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0003_auto_20210827_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gravitytable',
            old_name='sba1',
            new_name='sba',
        ),
        migrations.RemoveField(
            model_name='gravitytable',
            name='sba2',
        ),
    ]
