# Generated by Django 3.1.13 on 2021-09-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0004_auto_20210902_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='gravitytable',
            name='svd',
            field=models.TextField(null=True),
        ),
    ]
