# Generated by Django 3.1.13 on 2021-08-24 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gravity', '0005_auto_20210820_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.TextField(null=True)),
                ('y', models.TextField(null=True)),
                ('z', models.TextField(null=True)),
                ('FA', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilayah_ukur', models.CharField(max_length=100, null=True)),
                ('file_input', models.FileField(default='DEFAULT', upload_to='upload/')),
                ('delimiter', models.CharField(max_length=100)),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='GravityTable',
        ),
        migrations.DeleteModel(
            name='InputModel',
        ),
        migrations.AddField(
            model_name='datamodel',
            name='file_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gravity.filemodel'),
        ),
    ]
