# Generated by Django 3.1.13 on 2021-11-24 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0005_gravitytable_svd'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridTable',
            fields=[
                ('grid_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gravity.gravitytable')),
                ('x_grid', models.TextField(null=True)),
                ('y_grid', models.TextField(null=True)),
                ('sba_interpolate', models.TextField(null=True)),
            ],
        ),
    ]
