# Generated by Django 3.1.13 on 2021-11-25 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0006_gridtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gravitytable',
            name='svd',
        ),
        migrations.AddField(
            model_name='gridtable',
            name='n_grid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gridtable',
            name='grid_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gravity.gravitytable'),
        ),
    ]
