# Generated by Django 3.1.13 on 2021-08-25 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0006_auto_20210824_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamodel',
            name='file_id',
        ),
        migrations.AddField(
            model_name='datamodel',
            name='file_asal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gravity.filemodel'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file_input',
            field=models.FileField(upload_to=''),
        ),
    ]
