# Generated by Django 3.1.13 on 2021-11-25 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0007_auto_20211125_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridtable',
            name='grid_ref',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gravity.gravitytable'),
        ),
    ]
