# Generated by Django 3.1.13 on 2021-11-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0008_auto_20211125_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridtable',
            name='sample',
            field=models.IntegerField(null=True),
        ),
    ]
