# Generated by Django 3.1.13 on 2021-12-17 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0010_auto_20211205_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectralTable',
            fields=[
                ('spectral_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gravity.gridtable')),
            ],
        ),
    ]
