# Generated by Django 3.1.13 on 2021-12-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0011_spectraltable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gridtable',
            old_name='k',
            new_name='elev_interpolate',
        ),
        migrations.RenameField(
            model_name='gridtable',
            old_name='lnA_1',
            new_name='fa_interpolate',
        ),
        migrations.RemoveField(
            model_name='gridtable',
            name='lnA_2',
        ),
        migrations.RemoveField(
            model_name='gridtable',
            name='lnA_3',
        ),
        migrations.AddField(
            model_name='spectraltable',
            name='k',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spectraltable',
            name='lnA_1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spectraltable',
            name='lnA_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spectraltable',
            name='lnA_3',
            field=models.TextField(null=True),
        ),
    ]
