# Generated by Django 3.1.13 on 2022-01-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0012_auto_20211217_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridtable',
            name='z_interpolate',
            field=models.TextField(null=True),
        ),
    ]
