# Generated by Django 3.1.13 on 2022-01-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0013_gridtable_z_interpolate'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridtable',
            name='regional',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gridtable',
            name='residual',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='SpectralTable',
        ),
    ]
